name: environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - seaborn
    - ipywidgets
    - jupyter_contrib_nbextensions
